### ISSUE TITLE
Container fails to initialize because Java 17 can't be installed

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang-devcontainer-template#2]
Tested a new [repo](https://github.com/fbricon/jbangdemo) in codespaces:

```
2022-11-07 10:46:11.483Z: #6 ERROR: executor failed running [/bin/sh -c bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh              && sdk install jbang && jbang jdk install 17"]: exit code: 3
2022-11-07 10:46:11.651Z: ------
2022-11-07 10:46:11.651Z:  > [dev_container_auto_added_stage_label 3/3] RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh              && sdk install jbang && jbang jdk install 17":
2022-11-07 10:46:11.651Z: #6 9.028 Installing: jbang 0.99.1
2022-11-07 10:46:11.651Z: #6 9.092 Done installing!
2022-11-07 10:46:11.651Z: #6 9.092 
2022-11-07 10:46:11.651Z: #6 9.092 
2022-11-07 10:46:11.651Z: #6 9.092 Setting jbang 0.99.1 as default.
2022-11-07 10:46:11.651Z: #6 11.24 [jbang] Downloading JDK 17. Be patient, this can take several minutes...
2022-11-07 10:46:11.651Z: #6 58.90 [jbang] Installing JDK 17...
2022-11-07 10:46:11.651Z: #6 59.69 [jbang] [ERROR] Required Java version not possible to download or install. You can run with '--java 11' to force using the default installed Java.
2022-11-07 10:46:11.651Z: #6 59.69 [jbang] [ERROR] Unable to download or install JDK version 17
2022-11-07 10:46:11.651Z: #6 59.69 [jbang] Run with --verbose for more details
2022-11-07 10:46:11.651Z: ------
2022-11-07 10:46:11.651Z: ERROR: failed to solve: executor failed running [/bin/sh -c bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh              && sdk install jbang && jbang jdk install 17"]: exit code: 3
2022-11-07 10:46:11.651Z: Stop (75718 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.23.2-1667817895886/Dockerfile-with-features -t vsc-jbangdemo-e5367a0f93c7f8772653e6d8ccb08638 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/jbangdemo/.devcontainer
2022-11-07 10:46:11.651Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.23.2-1667817895886/Dockerfile-with-features -t vsc-jbangdemo-e5367a0f93c7f8772653e6d8ccb08638 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/jbangdemo/.devcontainer
2022-11-07 10:46:11.651Z:     at doe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1888:1635)
2022-11-07 10:46:11.651Z:     at runMicrotasks (<anonymous>)
2022-11-07 10:46:11.651Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-11-07 10:46:11.651Z:     at async pF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1887:1973)
2022-11-07 10:46:11.651Z:     at async eT (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1887:901)
2022-11-07 10:46:11.651Z:     at async voe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1893:2049)
2022-11-07 10:46:11.651Z:     at async Xf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1893:3212)
2022-11-07 10:46:11.652Z:     at async Jae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2013:15058)
2022-11-07 10:46:11.652Z:     at async Wae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2013:14812)
2022-11-07 10:46:11.652Z: Stop (225557 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/jbangdemo --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/jbangdemo/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-11-07 10:46:11.652Z: Exit code 1

```

**Comment by quintesse** [comment]
Any chance you could add a `--verbose` to that invocation and try again?
